Encode act_fn as hparam, use scratch buffers
monatis/clip.cpp pull request #13
Opened 2023-06-23 19:47 UTC by monatis

Closes 10 and #12

Will be open for some time for regression tests.

2023-06-23 22:57 UTC, Green-Sky requested changes

2023-06-23 22:57 UTC, Green-Sky commented on clip.cpp
> +            cur = ggml_gelu_quick_inplace(ctx0, cur);
:)

2023-06-24 07:56 UTC, monatis commented on clip.cpp
> +            cur = ggml_gelu_quick_inplace(ctx0, cur);
Quick GELU for everyone!11! :D

2023-06-24 09:55 UTC, Green-Sky approved these changes
gonna test this later :)
the reduces memory usage looks very good

2023-06-24 10:11 UTC, Green-Sky commented
can you align the model hyperparameter output?
```
clip_model_load: num_positions   = 77
clip_model_load: t_hidden_size  = 512
clip_model_load: t_n_intermediate  = 2048
clip_model_load: t_n_head  = 8
clip_model_load: t_n_layer = 12
clip_model_load: image_size = 224
clip_model_load: patch_size   = 32
clip_model_load: v_hidden_size  = 768
clip_model_load: v_n_intermediate  = 3072
clip_model_load: v_n_head  = 12
clip_model_load: v_n_layer = 12
clip_model_load: use_gelu     = 1
clip_model_load: ftype     = 1
```
looks very funky as is

2023-06-24 10:42 UTC, monatis commented
yeah it definitely needs some polishing. will have a look.

2023-06-24 11:05 UTC, Green-Sky commented
with pr:
```
$ bin/zsl -m ../models/laion_clip-vit-h-14-laion2b-s32b-b79k/ggml-model-f16.bin.new --image ../tests/red_apple.jpg --text dog --text apple --text human --text photo --text drawing --text red --text blue
...
apple = 0.1614
red = 0.1451
photo = 0.1450
human = 0.1417
drawing = 0.1395
blue = 0.1353
dog = 0.1320
```

master:
```
$ bin/zsl -m ../models/laion_clip-vit-h-14-laion2b-s32b-b79k/ggml-model-f16.bin.old --image ../tests/red_apple.jpg --text dog --text apple --text human --text photo --text drawing --text red --text blue
...
apple = 0.1592
red = 0.1445
photo = 0.1433
drawing = 0.1421
human = 0.1420
blue = 0.1358
dog = 0.1332
```

yea, values are better. but I'm still surprised how little difference this makes.

2023-06-24 11:34 UTC, monatis commented
> I'm still surprised how little difference this makes

It may even be worse in rare cases, but as you said single-instance tests are not so informatory. We still need a proper benchmarking. Maybe I should prioritize it soon.

After merging this PR, I can take on it. And, we can write a Medium post once benchmarking is done and the image search example is merged.

2023-06-24 11:37 UTC, Green-Sky commented
hm, i kinda miss the '=' or a ':'
```
n_vocab            49408
num_positions      77
t_hidden_size      1024
t_n_intermediate   4096
t_projection_dim   1024
t_n_head           16
t_n_layer          24

clip_model_load: vision model hparams
image_size             224
patch_size         14
v_hidden_size      1280
v_n_intermediate   5120
v_projection_dim   1024
v_n_head           16
v_n_layer          32

use_gelu           1
ftype              3
```

> It may even be worse in rare cases, but as you said single-instance tests are not so informatory. We still need a proper benchmarking. Maybe I should prioritize it soon.

yea, will have to look at common datasets, and make sure the models were not trained on the test data.

> After merging this PR, I can take on it. And, we can write a Medium post once benchmarking is done and the image search example is merged.

haha, yea.

2023-06-24 11:42 UTC, monatis commented
> hm, i kinda miss the '=' or a ':'


Do you prefer that one? I just thought of printing it out in some kind of 'tabular layout' based on the column width, i.e., string length.

2023-06-24 11:56 UTC, Green-Sky commented
> > hm, i kinda miss the '=' or a ':'
> 
> Do you prefer that one? I just thought of printing it out in some kind of 'tabular layout' based on the column width, i.e., string length.

hm, its fine i suppose. (if you fix the `image_size` )

2023-06-24 12:09 UTC, merged